POST http://localhost:3000/reports/create_report
Content-Type: application/json

{
    "maker": "ford",
    "model": "ST-MTP",
    "year": 1982,
    "mileage": 50460,
    "lng": 45,
    "lat": 45,
    "price": 25000
}

### edit an existing report
POST  http://localhost:3000/reports/edit/54
content-type: application/json

{
    "maker": "VuongPham",
    "price": 54000,
    "model": "VinFast",
    "year": 2022,
    "lng": 10,
    "lat": 11,
    "mileage": 13540
}

### Get an estimate price for the existing car
POST http://localhost:3000/reports/estimate
content-type: application/json

{
    "maker": "VinVuong"
}